<?php

namespace NP\workflow;

use NP\core\AbstractGateway;

class WFRuleTypeGateway extends AbstractGateway {
    protected $pk = 'wfruletype_id';
    protected $table = 'wfruletype';

	const PURCHASE_ORDER_TOTAL_AMOUNT = 1;
	const INVOICE_TOTAL_AMOUNT = 2;
	const BUDGET_AMOUNT_BY_GL_CODE = 3;
	const DELEGATION = 4;
	const APPROVAL_NOTIFICATION_EMAIL = 5;
	const SPECIFIC_VENDOR = 6;
	const INVOICE_BY_GL_CODE = 7;
	const PURCHASE_ORDER_BY_GL_CODE = 8;
	const BUDGET_AMOUNT_BY_GL_CATEGORY = 9;
	const INVOICE_BY_GL_CATEGORY = 10;
	const PURCHASE_ORDER_BY_GL_CATEGORY = 11;
	const BUDGET_OVERAGE_NOTIFICATION_EMAIL = 12;
	const YEARLY_BUDGET_BY_GL_CODE = 13;
	const YEARLY_BUDGET_BY_GL_CATEGORY = 14;
	const OPTIONAL_WORKFLOW = 15;
	const SPECIFIC_VENDOR_MASTER_RULE = 16;
	const VENDOR_ESTIMATE_PERCENTAGE_VARIANCE = 17;
	const VENDOR_ESTIMATE_TOTAL_DOLLAR_AMOUNT = 18;
	const VENDOR_ESTIMATE_DOLLAR_VARIANCE = 19;
	const CONVERTED_INVOICES = 20;
	const INVOICE_BY_GL_JOB_CODE = 21;
	const PURCHASE_ORDER_BY_GL_JOB_CODE = 22;
	const RECEIPT_TOTAL_AMOUNT = 23;
	const INVOICE_BY_CONTRACT_CODE = 24;
	const PURCHASE_ORDER_BY_CONTRACT_CODE = 25;
	const INVOICE_BY_CONTRACT_CODE_MASTER = 26;
	const PURCHASE_ORDER_BY_CONTRACT_CODE_MASTER = 27;
	const INVOICE_TOTAL_BY_PAY_BY = 28;
	const YTD_BUDGET_PERCENT_OVERAGE_BY_GL_CODE = 29;
	const YTD_BUDGET_PERCENT_OVERAGE_BY_GL_CATEGORY = 30;
	const MTD_BUDGET_PERCENT_OVERAGE_BY_GL_CODE = 31;
	const MTD_BUDGET_PERCENT_OVERAGE_BY_GL_CATEGORY = 32;
	const YTD_BUDGET_OVERAGE_BY_GL_CODE = 33;
	const YTD_BUDGET_OVERAGE_BY_GL_CATEGORY = 34;
	const PO_ITEM_AMOUNT_BY_DEPARTMENT = 35;
	const INVOICE_ITEM_AMOUNT_BY_DEPARTMENT = 36;
	const RECEIPT_ITEM_TOTAL_BY_GL_CODE = 37;
	const RECEIPT_ITEM_TOTAL_BY_GL_CATEGORY = 38;
}
