<?php
/**
 * File for the class which returns the class map definition
 * @package NPSoap
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 * @version 20130912-01
 * @date 2013-09-16
 */
/**
 * Class which returns the class map definition by the static method NPSoapClassMap::classMap()
 * @package NPSoap
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 * @version 20130912-01
 * @date 2013-09-16
 */
class NPSoapClassMap
{
	/**
	 * This method returns the array containing the mapping between WSDL structs and generated classes
	 * This array is sent to the SoapClient when calling the WS
	 * @return array
	 */
	final public static function classMap()
	{
		return array (
  'ErrCodes' => 'NPSoapStructErrCodes',
  'Login' => 'NPSoapStructLogin',
  'LoginResponse' => 'NPSoapStructLoginResponse',
  'LoginResult' => 'NPSoapStructLoginResult',
  'PNGETDATA' => 'NPSoapStructPNGETDATA',
  'PNGETDATAResponse' => 'NPSoapStructPNGETDATAResponse',
  'PNGETDATAResult' => 'NPSoapStructPNGETDATAResult',
  'PN_FINALIZE_JOBCOSTING' => 'NPSoapStructPN_FINALIZE_JOBCOSTING',
  'PN_FINALIZE_JOBCOSTINGResponse' => 'NPSoapStructPN_FINALIZE_JOBCOSTINGResponse',
  'PN_GET_DATA' => 'NPSoapStructPN_GET_DATA',
  'PN_GET_DATAResponse' => 'NPSoapStructPN_GET_DATAResponse',
  'PN_GET_DATAResult' => 'NPSoapStructPN_GET_DATAResult',
  'PN_GET_INVOICEITEMS' => 'NPSoapStructPN_GET_INVOICEITEMS',
  'PN_GET_INVOICEITEMSResponse' => 'NPSoapStructPN_GET_INVOICEITEMSResponse',
  'PN_GET_INVOICEITEMSResult' => 'NPSoapStructPN_GET_INVOICEITEMSResult',
  'PN_GET_INVOICES' => 'NPSoapStructPN_GET_INVOICES',
  'PN_GET_INVOICESResponse' => 'NPSoapStructPN_GET_INVOICESResponse',
  'PN_GET_INVOICESResult' => 'NPSoapStructPN_GET_INVOICESResult',
  'PN_GET_INVOICES_CONFIRM' => 'NPSoapStructPN_GET_INVOICES_CONFIRM',
  'PN_GET_INVOICES_CONFIRMResponse' => 'NPSoapStructPN_GET_INVOICES_CONFIRMResponse',
  'PN_GET_INVOICES_CONFIRMResult' => 'NPSoapStructPN_GET_INVOICES_CONFIRMResult',
  'PN_GET_KOFAX_PROPERTY' => 'NPSoapStructPN_GET_KOFAX_PROPERTY',
  'PN_GET_KOFAX_PROPERTYResponse' => 'NPSoapStructPN_GET_KOFAX_PROPERTYResponse',
  'PN_GET_KOFAX_PROPERTYResult' => 'NPSoapStructPN_GET_KOFAX_PROPERTYResult',
  'PN_GET_KOFAX_VENDORS' => 'NPSoapStructPN_GET_KOFAX_VENDORS',
  'PN_GET_KOFAX_VENDORSResponse' => 'NPSoapStructPN_GET_KOFAX_VENDORSResponse',
  'PN_GET_KOFAX_VENDORSResult' => 'NPSoapStructPN_GET_KOFAX_VENDORSResult',
  'PN_GET_POITEMS' => 'NPSoapStructPN_GET_POITEMS',
  'PN_GET_POITEMSResponse' => 'NPSoapStructPN_GET_POITEMSResponse',
  'PN_GET_POITEMSResult' => 'NPSoapStructPN_GET_POITEMSResult',
  'PN_GET_PURCHASEORDERS' => 'NPSoapStructPN_GET_PURCHASEORDERS',
  'PN_GET_PURCHASEORDERSResponse' => 'NPSoapStructPN_GET_PURCHASEORDERSResponse',
  'PN_GET_PURCHASEORDERSResult' => 'NPSoapStructPN_GET_PURCHASEORDERSResult',
  'PN_GET_RCTITEMS' => 'NPSoapStructPN_GET_RCTITEMS',
  'PN_GET_RCTITEMSResponse' => 'NPSoapStructPN_GET_RCTITEMSResponse',
  'PN_GET_RCTITEMSResult' => 'NPSoapStructPN_GET_RCTITEMSResult',
  'PN_GET_RECEIPTS' => 'NPSoapStructPN_GET_RECEIPTS',
  'PN_GET_RECEIPTSResponse' => 'NPSoapStructPN_GET_RECEIPTSResponse',
  'PN_GET_RECEIPTSResult' => 'NPSoapStructPN_GET_RECEIPTSResult',
  'PN_GET_SCHEDULER' => 'NPSoapStructPN_GET_SCHEDULER',
  'PN_GET_SCHEDULERResponse' => 'NPSoapStructPN_GET_SCHEDULERResponse',
  'PN_GET_SCHEDULER_CUSTOM' => 'NPSoapStructPN_GET_SCHEDULER_CUSTOM',
  'PN_GET_SCHEDULER_CUSTOMResponse' => 'NPSoapStructPN_GET_SCHEDULER_CUSTOMResponse',
  'PN_GET_VENDORCOMBO_CONFIRM' => 'NPSoapStructPN_GET_VENDORCOMBO_CONFIRM',
  'PN_GET_VENDORCOMBO_CONFIRMResponse' => 'NPSoapStructPN_GET_VENDORCOMBO_CONFIRMResponse',
  'PN_GET_VENDORCOMBO_CONFIRMResult' => 'NPSoapStructPN_GET_VENDORCOMBO_CONFIRMResult',
  'PN_GET_VENDORS' => 'NPSoapStructPN_GET_VENDORS',
  'PN_GET_VENDORSResponse' => 'NPSoapStructPN_GET_VENDORSResponse',
  'PN_GET_VENDORSResult' => 'NPSoapStructPN_GET_VENDORSResult',
  'PN_GET_VENDOR_INSURANCE' => 'NPSoapStructPN_GET_VENDOR_INSURANCE',
  'PN_GET_VENDOR_INSURANCEResponse' => 'NPSoapStructPN_GET_VENDOR_INSURANCEResponse',
  'PN_GET_VENDOR_INSURANCEResult' => 'NPSoapStructPN_GET_VENDOR_INSURANCEResult',
  'PN_SAVE_QUERY_RESULT' => 'NPSoapStructPN_SAVE_QUERY_RESULT',
  'PN_SAVE_QUERY_RESULTResponse' => 'NPSoapStructPN_SAVE_QUERY_RESULTResponse',
  'PN_SAVE_QUERY_RESULTResult' => 'NPSoapStructPN_SAVE_QUERY_RESULTResult',
  'PN_SET_ACTUAL' => 'NPSoapStructPN_SET_ACTUAL',
  'PN_SET_ACTUALResponse' => 'NPSoapStructPN_SET_ACTUALResponse',
  'PN_SET_ACTUALResult' => 'NPSoapStructPN_SET_ACTUALResult',
  'PN_SET_BUDGET' => 'NPSoapStructPN_SET_BUDGET',
  'PN_SET_BUDGETResponse' => 'NPSoapStructPN_SET_BUDGETResponse',
  'PN_SET_BUDGETResult' => 'NPSoapStructPN_SET_BUDGETResult',
  'PN_SET_CHANGEORDER' => 'NPSoapStructPN_SET_CHANGEORDER',
  'PN_SET_CHANGEORDERResponse' => 'NPSoapStructPN_SET_CHANGEORDERResponse',
  'PN_SET_CHANGEORDERResult' => 'NPSoapStructPN_SET_CHANGEORDERResult',
  'PN_SET_CONTRACT' => 'NPSoapStructPN_SET_CONTRACT',
  'PN_SET_CONTRACTBUDGET' => 'NPSoapStructPN_SET_CONTRACTBUDGET',
  'PN_SET_CONTRACTBUDGETResponse' => 'NPSoapStructPN_SET_CONTRACTBUDGETResponse',
  'PN_SET_CONTRACTBUDGETResult' => 'NPSoapStructPN_SET_CONTRACTBUDGETResult',
  'PN_SET_CONTRACTResponse' => 'NPSoapStructPN_SET_CONTRACTResponse',
  'PN_SET_CONTRACTResult' => 'NPSoapStructPN_SET_CONTRACTResult',
  'PN_SET_COSTCODE' => 'NPSoapStructPN_SET_COSTCODE',
  'PN_SET_COSTCODEResponse' => 'NPSoapStructPN_SET_COSTCODEResponse',
  'PN_SET_COSTCODEResult' => 'NPSoapStructPN_SET_COSTCODEResult',
  'PN_SET_DATA' => 'NPSoapStructPN_SET_DATA',
  'PN_SET_DATAResponse' => 'NPSoapStructPN_SET_DATAResponse',
  'PN_SET_DATAResult' => 'NPSoapStructPN_SET_DATAResult',
  'PN_SET_ERRORCODES' => 'NPSoapStructPN_SET_ERRORCODES',
  'PN_SET_ERRORCODESResponse' => 'NPSoapStructPN_SET_ERRORCODESResponse',
  'PN_SET_ERRORCODESResult' => 'NPSoapStructPN_SET_ERRORCODESResult',
  'PN_SET_GLACCOUNT' => 'NPSoapStructPN_SET_GLACCOUNT',
  'PN_SET_GLACCOUNTResponse' => 'NPSoapStructPN_SET_GLACCOUNTResponse',
  'PN_SET_GLACCOUNTResult' => 'NPSoapStructPN_SET_GLACCOUNTResult',
  'PN_SET_INVOICEITEMS' => 'NPSoapStructPN_SET_INVOICEITEMS',
  'PN_SET_INVOICEITEMSResponse' => 'NPSoapStructPN_SET_INVOICEITEMSResponse',
  'PN_SET_INVOICEITEMSResult' => 'NPSoapStructPN_SET_INVOICEITEMSResult',
  'PN_SET_INVOICEPAYMENTS' => 'NPSoapStructPN_SET_INVOICEPAYMENTS',
  'PN_SET_INVOICEPAYMENTSResponse' => 'NPSoapStructPN_SET_INVOICEPAYMENTSResponse',
  'PN_SET_INVOICEPAYMENTSResult' => 'NPSoapStructPN_SET_INVOICEPAYMENTSResult',
  'PN_SET_INVOICES' => 'NPSoapStructPN_SET_INVOICES',
  'PN_SET_INVOICESResponse' => 'NPSoapStructPN_SET_INVOICESResponse',
  'PN_SET_INVOICESResult' => 'NPSoapStructPN_SET_INVOICESResult',
  'PN_SET_INVOICES_POSTED' => 'NPSoapStructPN_SET_INVOICES_POSTED',
  'PN_SET_INVOICES_POSTEDResponse' => 'NPSoapStructPN_SET_INVOICES_POSTEDResponse',
  'PN_SET_INVOICES_POSTEDResult' => 'NPSoapStructPN_SET_INVOICES_POSTEDResult',
  'PN_SET_JOBCODE' => 'NPSoapStructPN_SET_JOBCODE',
  'PN_SET_JOBCODEResponse' => 'NPSoapStructPN_SET_JOBCODEResponse',
  'PN_SET_JOBCODEResult' => 'NPSoapStructPN_SET_JOBCODEResult',
  'PN_SET_JOBCODES' => 'NPSoapStructPN_SET_JOBCODES',
  'PN_SET_JOBCODESResponse' => 'NPSoapStructPN_SET_JOBCODESResponse',
  'PN_SET_JOBCODESResult' => 'NPSoapStructPN_SET_JOBCODESResult',
  'PN_SET_JOBPHASE' => 'NPSoapStructPN_SET_JOBPHASE',
  'PN_SET_JOBPHASEResponse' => 'NPSoapStructPN_SET_JOBPHASEResponse',
  'PN_SET_JOBPHASEResult' => 'NPSoapStructPN_SET_JOBPHASEResult',
  'PN_SET_JOBTYPE' => 'NPSoapStructPN_SET_JOBTYPE',
  'PN_SET_JOBTYPEResponse' => 'NPSoapStructPN_SET_JOBTYPEResponse',
  'PN_SET_JOBTYPEResult' => 'NPSoapStructPN_SET_JOBTYPEResult',
  'PN_SET_KOFAX_PROPERTY' => 'NPSoapStructPN_SET_KOFAX_PROPERTY',
  'PN_SET_KOFAX_PROPERTYResponse' => 'NPSoapStructPN_SET_KOFAX_PROPERTYResponse',
  'PN_SET_KOFAX_PROPERTYResult' => 'NPSoapStructPN_SET_KOFAX_PROPERTYResult',
  'PN_SET_KOFAX_VENDOR' => 'NPSoapStructPN_SET_KOFAX_VENDOR',
  'PN_SET_KOFAX_VENDORResponse' => 'NPSoapStructPN_SET_KOFAX_VENDORResponse',
  'PN_SET_KOFAX_VENDORResult' => 'NPSoapStructPN_SET_KOFAX_VENDORResult',
  'PN_SET_PHASECODE' => 'NPSoapStructPN_SET_PHASECODE',
  'PN_SET_PHASECODEResponse' => 'NPSoapStructPN_SET_PHASECODEResponse',
  'PN_SET_PHASECODEResult' => 'NPSoapStructPN_SET_PHASECODEResult',
  'PN_SET_POITEMS_CONFIRM' => 'NPSoapStructPN_SET_POITEMS_CONFIRM',
  'PN_SET_POITEMS_CONFIRMResponse' => 'NPSoapStructPN_SET_POITEMS_CONFIRMResponse',
  'PN_SET_POITEMS_CONFIRMResult' => 'NPSoapStructPN_SET_POITEMS_CONFIRMResult',
  'PN_SET_PURCHASEORDERS_CONFIRM' => 'NPSoapStructPN_SET_PURCHASEORDERS_CONFIRM',
  'PN_SET_PURCHASEORDERS_CONFIRMResponse' => 'NPSoapStructPN_SET_PURCHASEORDERS_CONFIRMResponse',
  'PN_SET_PURCHASEORDERS_CONFIRMResult' => 'NPSoapStructPN_SET_PURCHASEORDERS_CONFIRMResult',
  'PN_SET_RECEIPTITEMS_CONFIRM' => 'NPSoapStructPN_SET_RECEIPTITEMS_CONFIRM',
  'PN_SET_RECEIPTITEMS_CONFIRMResponse' => 'NPSoapStructPN_SET_RECEIPTITEMS_CONFIRMResponse',
  'PN_SET_RECEIPTITEMS_CONFIRMResult' => 'NPSoapStructPN_SET_RECEIPTITEMS_CONFIRMResult',
  'PN_SET_RECEIPTS_CONFIRM' => 'NPSoapStructPN_SET_RECEIPTS_CONFIRM',
  'PN_SET_RECEIPTS_CONFIRMResponse' => 'NPSoapStructPN_SET_RECEIPTS_CONFIRMResponse',
  'PN_SET_RECEIPTS_CONFIRMResult' => 'NPSoapStructPN_SET_RECEIPTS_CONFIRMResult',
  'PN_SET_SCHEDULER' => 'NPSoapStructPN_SET_SCHEDULER',
  'PN_SET_SCHEDULERResponse' => 'NPSoapStructPN_SET_SCHEDULERResponse',
  'PN_SET_VENDORCOMBO' => 'NPSoapStructPN_SET_VENDORCOMBO',
  'PN_SET_VENDORCOMBOResponse' => 'NPSoapStructPN_SET_VENDORCOMBOResponse',
  'PN_SET_VENDORCOMBOResult' => 'NPSoapStructPN_SET_VENDORCOMBOResult',
  'PN_SET_VENDOR_INSURANCE' => 'NPSoapStructPN_SET_VENDOR_INSURANCE',
  'PN_SET_VENDOR_INSURANCEResponse' => 'NPSoapStructPN_SET_VENDOR_INSURANCEResponse',
  'PN_SET_VENDOR_INSURANCEResult' => 'NPSoapStructPN_SET_VENDOR_INSURANCEResult',
  'PN_SET_VENDOR_INSURANCE_CONFIRM' => 'NPSoapStructPN_SET_VENDOR_INSURANCE_CONFIRM',
  'PN_SET_VENDOR_INSURANCE_CONFIRMResponse' => 'NPSoapStructPN_SET_VENDOR_INSURANCE_CONFIRMResponse',
  'PN_SET_VENDOR_INSURANCE_CONFIRMResult' => 'NPSoapStructPN_SET_VENDOR_INSURANCE_CONFIRMResult',
  'PN_VALIDATE_XML' => 'NPSoapStructPN_VALIDATE_XML',
  'PN_VALIDATE_XMLResponse' => 'NPSoapStructPN_VALIDATE_XMLResponse',
  'SecurityHeader' => 'NPSoapStructSecurityHeader',
  'actuals' => 'NPSoapStructActuals',
  'budgets' => 'NPSoapStructBudgets',
  'changeorders' => 'NPSoapStructChangeorders',
  'contractbudgets' => 'NPSoapStructContractbudgets',
  'contracts' => 'NPSoapStructContracts',
  'costcodes' => 'NPSoapStructCostcodes',
  'data' => 'NPSoapStructData',
  'glaccount' => 'NPSoapStructGlaccount',
  'invoiceconfirmlist' => 'NPSoapStructInvoiceconfirmlist',
  'invoiceitems' => 'NPSoapStructInvoiceitems',
  'invoicepayment' => 'NPSoapStructInvoicepayment',
  'invoiceposted' => 'NPSoapStructInvoiceposted',
  'invoices' => 'NPSoapStructInvoices',
  'jobcodes' => 'NPSoapStructJobcodes',
  'jobphases' => 'NPSoapStructJobphases',
  'jobtypes' => 'NPSoapStructJobtypes',
  'parameters' => 'NPSoapStructParameters',
  'phasecodes' => 'NPSoapStructPhasecodes',
  'properties' => 'NPSoapStructProperties',
  'vendorcombo' => 'NPSoapStructVendorcombo',
  'vendorconfirmlist' => 'NPSoapStructVendorconfirmlist',
  'vendors' => 'NPSoapStructVendors',
  'xQuery' => 'NPSoapStructXQuery',
);
	}
}
?>