/**
 * Store for Countries
 *
 * @author Thomas Messier
 */
Ext.define('NP.store.system.Countries', {
	extend: 'Ext.data.Store',
	
	fields: [
		{ name: 'id', type: 'int' },
		{ name: 'name' },
		{ name: 'order', type: 'int' },
		{ name: 'active', type: 'int' }
	],
	
	data: [
		{ id: 125, name: 'United States', order: 1, active: 1 },
		{ id: 1, name: 'Afghanistan', order: 2, active: 1 },
		{ id: 2, name: 'Albania', order: 2, active: 1 },
		{ id: 3, name: 'Algeria', order: 2, active: 1 },
		{ id: 4, name: 'Angola', order: 2, active: 1 },
		{ id: 5, name: 'Argentina', order: 2, active: 1 },
		{ id: 6, name: 'Armenia', order: 2, active: 1 },
		{ id: 7, name: 'Australia', order: 2, active: 1 },
		{ id: 8, name: 'Austria', order: 2, active: 1 },
		{ id: 9, name: 'Azerbaijan', order: 2, active: 1 },
		{ id: 10, name: 'Bangladesh', order: 2, active: 1 },
		{ id: 11, name: 'Belarus', order: 2, active: 1 },
		{ id: 12, name: 'Belgium', order: 2, active: 1 },
		{ id: 13, name: 'Benin', order: 2, active: 1 },
		{ id: 133, name: 'Bermuda', order: 2, active: 1 },
		{ id: 14, name: 'Bolivia', order: 2, active: 1 },
		{ id: 15, name: 'Bosnia and Herzegovina', order: 2, active: 1 },
		{ id: 16, name: 'Botswana', order: 2, active: 1 },
		{ id: 17, name: 'Brazil', order: 2, active: 1 },
		{ id: 18, name: 'Bulgaria', order: 2, active: 1 },
		{ id: 19, name: 'Burkina Faso', order: 2, active: 1 },
		{ id: 20, name: 'Burundi', order: 2, active: 1 },
		{ id: 21, name: 'Cambodia', order: 2, active: 1 },
		{ id: 22, name: 'Cameroon', order: 2, active: 1 },
		{ id: 23, name: 'Canada', order: 2, active: 1 },
		{ id: 24, name: 'Chad', order: 2, active: 1 },
		{ id: 25, name: 'Chile', order: 2, active: 1 },
		{ id: 26, name: 'China', order: 2, active: 1 },
		{ id: 27, name: 'Colombia', order: 2, active: 1 },
		{ id: 28, name: 'Costa Rica', order: 2, active: 1 },
		{ id: 29, name: 'Croatia', order: 2, active: 1 },
		{ id: 30, name: 'Cuba', order: 2, active: 1 },
		{ id: 31, name: 'Cyprus', order: 2, active: 1 },
		{ id: 32, name: 'Czech Republic', order: 2, active: 1 },
		{ id: 33, name: 'Denmark', order: 2, active: 1 },
		{ id: 34, name: 'Dominican Republic', order: 2, active: 1 },
		{ id: 35, name: 'Ecuador', order: 2, active: 1 },
		{ id: 36, name: 'Egypt', order: 2, active: 1 },
		{ id: 37, name: 'El Salvador', order: 2, active: 1 },
		{ id: 38, name: 'Estonia', order: 2, active: 1 },
		{ id: 39, name: 'Ethiopia', order: 2, active: 1 },
		{ id: 40, name: 'Finland', order: 2, active: 1 },
		{ id: 41, name: 'France', order: 2, active: 1 },
		{ id: 42, name: 'Georgia', order: 2, active: 1 },
		{ id: 43, name: 'Germany', order: 2, active: 1 },
		{ id: 44, name: 'Ghana', order: 2, active: 1 },
		{ id: 45, name: 'Greece', order: 2, active: 1 },
		{ id: 46, name: 'Guatemala', order: 2, active: 1 },
		{ id: 47, name: 'Haiti', order: 2, active: 1 },
		{ id: 48, name: 'Honduras', order: 2, active: 1 },
		{ id: 49, name: 'Hungary', order: 2, active: 1 },
		{ id: 50, name: 'India', order: 2, active: 1 },
		{ id: 51, name: 'Indonesia', order: 2, active: 1 },
		{ id: 52, name: 'Iran', order: 2, active: 1 },
		{ id: 53, name: 'Iraq', order: 2, active: 1 },
		{ id: 54, name: 'Ireland', order: 2, active: 1 },
		{ id: 55, name: 'Israel', order: 2, active: 1 },
		{ id: 56, name: 'Italy', order: 2, active: 1 },
		{ id: 57, name: 'Jamaica', order: 2, active: 1 },
		{ id: 58, name: 'Japan', order: 2, active: 1 },
		{ id: 59, name: 'Jordan', order: 2, active: 1 },
		{ id: 60, name: 'Kazakhstan', order: 2, active: 1 },
		{ id: 61, name: 'Kenya', order: 2, active: 1 },
		{ id: 62, name: 'Kosovo', order: 2, active: 1 },
		{ id: 63, name: 'Kuwait', order: 2, active: 1 },
		{ id: 64, name: 'Kyrgyzstan', order: 2, active: 1 },
		{ id: 65, name: 'Latvia', order: 2, active: 1 },
		{ id: 66, name: 'Lebanon', order: 2, active: 1 },
		{ id: 67, name: 'Lithuania', order: 2, active: 1 },
		{ id: 68, name: 'Macedonia', order: 2, active: 1 },
		{ id: 69, name: 'Madagascar', order: 2, active: 1 },
		{ id: 70, name: 'Malawi', order: 2, active: 1 },
		{ id: 71, name: 'Malaysia', order: 2, active: 1 },
		{ id: 72, name: 'Mali', order: 2, active: 1 },
		{ id: 73, name: 'Mauritania', order: 2, active: 1 },
		{ id: 74, name: 'Mexico', order: 2, active: 1 },
		{ id: 75, name: 'Moldova', order: 2, active: 1 },
		{ id: 76, name: 'Montenegro', order: 2, active: 1 },
		{ id: 77, name: 'Morocco', order: 2, active: 1 },
		{ id: 78, name: 'Mozambique', order: 2, active: 1 },
		{ id: 79, name: 'Myanmar (Burma)', order: 2, active: 1 },
		{ id: 80, name: 'Nepal', order: 2, active: 1 },
		{ id: 81, name: 'Netherlands', order: 2, active: 1 },
		{ id: 82, name: 'New Zealand', order: 2, active: 1 },
		{ id: 83, name: 'Nicaragua', order: 2, active: 1 },
		{ id: 84, name: 'Niger', order: 2, active: 1 },
		{ id: 85, name: 'Nigeria', order: 2, active: 1 },
		{ id: 86, name: 'Norway', order: 2, active: 1 },
		{ id: 87, name: 'Pakistan', order: 2, active: 1 },
		{ id: 88, name: 'Palestinian Territory', order: 2, active: 1 },
		{ id: 89, name: 'Panama', order: 2, active: 1 },
		{ id: 90, name: 'Paraguay', order: 2, active: 1 },
		{ id: 91, name: 'Peru', order: 2, active: 1 },
		{ id: 92, name: 'Philippines', order: 2, active: 1 },
		{ id: 93, name: 'Poland', order: 2, active: 1 },
		{ id: 94, name: 'Portugal', order: 2, active: 1 },
		{ id: 95, name: 'Puerto Rico', order: 2, active: 1 },
		{ id: 96, name: 'Romania', order: 2, active: 1 },
		{ id: 97, name: 'Russia', order: 2, active: 1 },
		{ id: 98, name: 'Rwanda', order: 2, active: 1 },
		{ id: 99, name: 'Saudi Arabia', order: 2, active: 1 },
		{ id: 100, name: 'Senegal', order: 2, active: 1 },
		{ id: 101, name: 'Serbia', order: 2, active: 1 },
		{ id: 102, name: 'Sierra Leone', order: 2, active: 1 },
		{ id: 103, name: 'Singapore', order: 2, active: 1 },
		{ id: 104, name: 'Slovakia', order: 2, active: 1 },
		{ id: 105, name: 'Slovenia', order: 2, active: 1 },
		{ id: 106, name: 'South Africa', order: 2, active: 1 },
		{ id: 107, name: 'South Korea', order: 2, active: 1 },
		{ id: 108, name: 'Spain', order: 2, active: 1 },
		{ id: 109, name: 'Sri Lanka', order: 2, active: 1 },
		{ id: 110, name: 'Sudan', order: 2, active: 1 },
		{ id: 111, name: 'Sweden', order: 2, active: 1 },
		{ id: 112, name: 'Switzerland', order: 2, active: 1 },
		{ id: 113, name: 'Taiwan, Province of China', order: 2, active: 1 },
		{ id: 114, name: 'Tajikistan', order: 2, active: 1 },
		{ id: 115, name: 'Tanzania', order: 2, active: 1 },
		{ id: 116, name: 'Thailand', order: 2, active: 1 },
		{ id: 117, name: 'Togo', order: 2, active: 1 },
		{ id: 118, name: 'Trinidad & Tobago', order: 2, active: 1 },
		{ id: 119, name: 'Tunisia', order: 2, active: 1 },
		{ id: 120, name: 'Turkey', order: 2, active: 1 },
		{ id: 121, name: 'Uganda', order: 2, active: 1 },
		{ id: 122, name: 'Ukraine', order: 2, active: 1 },
		{ id: 123, name: 'United Arab Emirates', order: 2, active: 1 },
		{ id: 124, name: 'United Kingdom', order: 2, active: 1 },
		{ id: 126, name: 'Uruguay', order: 2, active: 1 },
		{ id: 127, name: 'Uzbekistan', order: 2, active: 1 },
		{ id: 128, name: 'Venezuela', order: 2, active: 1 },
		{ id: 129, name: 'Vietnam', order: 2, active: 1 },
		{ id: 130, name: 'Yemen', order: 2, active: 1 },
		{ id: 131, name: 'Zambia', order: 2, active: 1 },
		{ id: 132, name: 'Zimbabwe', order: 2, active: 1 }
	]
});